// Generates the Phase-E golden TS-written index.
//
// Runs the REAL TypeScript pipeline (`createZvecGrep` + `FakeEmbeddingModel`
// over a tiny fixture workspace) and snapshots the resulting storage dir
// (`files.zvec` + `index.zvec`) plus the exact `FileInfo`s the TS side
// reports. The Rust test `tests/ts_index_compat.rs` copies this snapshot
// to a tempdir and asserts the legacy importer reproduces those FileInfos.
//
// Regenerate with (from the zvec-grep-rs repo root):
//   node crates/zg-core/tests/golden/ts-index/gen-fixture.mjs
// Requires `../zvec-grep/node_modules` + `../zvec-grep/dist` (npm ci && npm run build).
// Network use at generation time: none beyond the npm install (the fake
// embedding model is deterministic and local).
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, cpSync, rmSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const zvecGrep = new URL("../../../../../../zvec-grep/", import.meta.url);
const { createZvecGrep } = await import(new URL("dist/index.js", zvecGrep).href);
const { createWorkspaceIndexStorage } = await import(new URL("dist/engine/storage/index.js", zvecGrep).href);
const { FakeEmbeddingModel } = await import(new URL("test/helpers/fake-embedding.mjs", zvecGrep).href);

const root = mkdtempSync(join(tmpdir(), "zvec-grep-ts-fixture-"));
mkdirSync(join(root, "src"), { recursive: true });
writeFileSync(join(root, "src", "hello.ts"), "export function greet(name: string): string {\n  return `hello, ${name}!`;\n}\n");
writeFileSync(join(root, "notes.md"), "# Notes\n\nSome pointer chasing: alpha beta gamma.\n\nUnicode caf\u00e9 na\u00efve \u4e2d\u6587.\n");
writeFileSync(join(root, "data.txt"), "plain text payload with retrieval words delta epsilon zeta\nsecond line here\n");

const service = await createZvecGrep({ root, embeddingModel: new FakeEmbeddingModel() });
try {
  await service.index({});
} finally {
  service.close();
}

function findFilesZvec(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "files.zvec") return full;
      const nested = findFilesZvec(full);
      if (nested) return nested;
    }
  }
  return null;
}
const filesZvec = findFilesZvec(root);
if (!filesZvec) throw new Error("generator: no files.zvec written under " + root);
const storagePath = dirname(filesZvec);

function findManifest(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (!entry.isDirectory()) {
      if (entry.name === "manifest.json") return full;
    } else if (entry.name !== "node_modules") {
      const nested = findManifest(full);
      if (nested) return nested;
    }
  }
  return null;
}
const manifestPath = findManifest(root);
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

const storage = createWorkspaceIndexStorage({ storagePath, readOnly: true });
let files;
const entityCounts = {};
try {
  files = storage.listFiles().sort((a, b) => a.relativePath.localeCompare(b.relativePath));
  for (const file of files) {
    entityCounts[file.relativePath] = storage.listEntitiesByFile(file.id).length;
  }
} finally {
  storage.close();
}

const outDir = join(here, "storage-template");
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
cpSync(join(storagePath, "files.zvec"), join(outDir, "files.zvec"), { recursive: true });
cpSync(join(storagePath, "index.zvec"), join(outDir, "index.zvec"), { recursive: true });

const expected = {
  provenance: "generated by gen-fixture.mjs via the real TS pipeline (createZvecGrep + FakeEmbeddingModel)",
  genRoot: root,
  workspaceIndexId: manifest.id,
  indexVersion: manifest.indexVersion,
  embedding: manifest.embedding,
  files,
  entityCounts,
};
writeFileSync(join(here, "expected.json"), JSON.stringify(expected, null, 2) + "\n");
console.log(`fixture root: ${root}`);
console.log(`storage: ${storagePath}`);
for (const f of files) {
  console.log(`  ${f.relativePath} kind=${f.kind} format=${f.format} entities=${entityCounts[f.relativePath]}`);
}
console.log(`snapshot: ${relative(process.cwd(), outDir)}`);
